# Generated by Django 4.0.5 on 2023-01-30 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team1_score',
            new_name='doubles_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team2_score',
            new_name='singles1_score',
        ),
        migrations.AddField(
            model_name='match',
            name='singles2_score',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='base.team'),
        ),
        migrations.AlterField(
            model_name='score',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='base.team'),
        ),
    ]
