# Generated by Django 4.0.5 on 2022-06-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(blank=True, max_length=200, null=True)),
                ('match1', models.CharField(blank=True, max_length=200, null=True)),
                ('match2', models.CharField(blank=True, max_length=200, null=True)),
                ('match3', models.CharField(blank=True, max_length=200, null=True)),
                ('match4', models.CharField(blank=True, max_length=200, null=True)),
                ('match5', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
